[package]
name = "systest"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
publish = false

[dependencies]
libc = "0.2"
boring-sys = { path = "../boring-sys" }

[build-dependencies]
ctest = "0.2"
