[package]
name = "hyper-boring"
version = "1.0.0"
authors = ["Steven Fackler <sfackler@gmail.com>", "Ivan Nikulin <ifaaan@gmail.com>"]
edition = "2018"
description = "Hyper TLS support via BoringSSL"
license = "MIT/Apache-2.0"
repository = "https://github.com/sfackler/hyper-boring"
readme = "README.md"
exclude = ["test/*"]

[features]
default = ["runtime"]

runtime = ["hyper/runtime"]

[dependencies]
antidote = "1.0.0"
bytes = "0.5"
http = "0.2"
hyper = { version = "0.13", default-features = false }
linked_hash_set = "0.1"
once_cell = "1.0"
boring = { version = "1.0.0", path = "../boring" }
boring-sys = { version = "1.0.0", path = "../boring-sys" }
tokio = "0.2"
tokio-boring = { version = "1.0.0", path = "../tokio-boring" }
tower-layer = "0.3"

[dev-dependencies]
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
