[package]
name = "boring-sys"
version = "1.0.0"
authors = ["Alex Crichton <alex@alexcrichton.com>",
           "Steven Fackler <sfackler@gmail.com>",
           "Ivan Nikulin <ifaaan@gmail.com>"]
license = "MIT"
description = "FFI bindings to BoringSSL"
repository = "https://github.com/inikulin/boring"
readme = "README.md"
categories = ["cryptography", "external-ffi-bindings"]

[dependencies]
libc = "0.2"

[build-dependencies]
cmake = "0.1"
